from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Trade(Base):
    """Trade execution records"""
    __tablename__ = 'trades'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.now, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    action = Column(String(20), nullable=False)  # BUY, SELL, STOP_LOSS, TAKE_PROFIT
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    value = Column(Float, nullable=False)
    commission = Column(Float, default=0.0)
    strategy_name = Column(String(100))
    bot_name = Column(String(50))
    portfolio_id = Column(Integer, ForeignKey('portfolios.id'))
    
    # Relationships
    portfolio = relationship("Portfolio", back_populates="trades")
    
    def __repr__(self):
        return f"<Trade {self.action} {self.quantity} {self.symbol} @ ${self.price}>"


class Portfolio(Base):
    """Portfolio snapshots and tracking"""
    __tablename__ = 'portfolios'
    
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)
    initial_capital = Column(Float, nullable=False)
    current_cash = Column(Float, nullable=False)
    total_value = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)
    is_active = Column(Boolean, default=True)
    
    # Relationships
    trades = relationship("Trade", back_populates="portfolio")
    snapshots = relationship("PortfolioSnapshot", back_populates="portfolio")
    
    def __repr__(self):
        return f"<Portfolio {self.name} ${self.total_value:.2f}>"


class PortfolioSnapshot(Base):
    """Historical portfolio values for tracking performance"""
    __tablename__ = 'portfolio_snapshots'
    
    id = Column(Integer, primary_key=True)
    portfolio_id = Column(Integer, ForeignKey('portfolios.id'), nullable=False)
    timestamp = Column(DateTime, default=datetime.now, index=True)
    total_value = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    positions_value = Column(Float, nullable=False)
    total_pnl = Column(Float, nullable=False)
    total_pnl_pct = Column(Float, nullable=False)
    num_positions = Column(Integer, default=0)
    
    # Relationships
    portfolio = relationship("Portfolio", back_populates="snapshots")
    
    def __repr__(self):
        return f"<Snapshot ${self.total_value:.2f} @ {self.timestamp}>"


class Bot(Base):
    """Trading bot instances"""
    __tablename__ = 'bots'
    
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text)
    portfolio_id = Column(Integer, ForeignKey('portfolios.id'), nullable=False)
    status = Column(String(20), default='stopped')  # stopped, running, paused, error
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)
    last_run_at = Column(DateTime)
    is_active = Column(Boolean, default=True)
    
    # Bot configuration (stored as JSON)
    config = Column(Text)  # JSON: symbols, strategies, risk params, etc.
    
    # Relationships
    portfolio = relationship("Portfolio")
    signals = relationship("Signal", back_populates="bot")
    
    def __repr__(self):
        return f"<Bot {self.name} ({self.status})>"


class Signal(Base):
    """Trading signals generated by strategies"""
    __tablename__ = 'signals'
    
    id = Column(Integer, primary_key=True)
    bot_id = Column(Integer, ForeignKey('bots.id'), index=True)
    timestamp = Column(DateTime, default=datetime.now, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    signal_type = Column(String(20), nullable=False)  # BUY, SELL, HOLD
    strategy_name = Column(String(100), nullable=False)
    price = Column(Float, nullable=False)
    confidence = Column(Float, default=1.0)
    executed = Column(Boolean, default=False)
    signal_metadata = Column(Text)  # JSON string for additional data
    
    # Relationships
    bot = relationship("Bot", back_populates="signals")
    
    def __repr__(self):
        return f"<Signal {self.signal_type} {self.symbol} by {self.strategy_name}>"


class Performance(Base):
    """Performance metrics and statistics"""
    __tablename__ = 'performance'
    
    id = Column(Integer, primary_key=True)
    portfolio_id = Column(Integer, ForeignKey('portfolios.id'))
    timestamp = Column(DateTime, default=datetime.now, index=True)
    period = Column(String(20))  # daily, weekly, monthly, all_time
    
    # Performance metrics
    total_return = Column(Float)
    total_return_pct = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    win_rate = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    profit_factor = Column(Float)
    
    def __repr__(self):
        return f"<Performance {self.period} Return: {self.total_return_pct:.2f}%>"


class Position(Base):
    """Current open positions"""
    __tablename__ = 'positions'
    
    id = Column(Integer, primary_key=True)
    portfolio_id = Column(Integer, ForeignKey('portfolios.id'))
    symbol = Column(String(20), nullable=False, index=True)
    quantity = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=False)
    entry_time = Column(DateTime, default=datetime.now)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    position_type = Column(String(10), default='LONG')  # LONG or SHORT
    is_open = Column(Boolean, default=True)
    closed_at = Column(DateTime)
    
    def __repr__(self):
        return f"<Position {self.symbol} {self.quantity} @ ${self.entry_price}>"
